language: python
sudo: false
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
matrix:
  include:
    - python: "2.6"
      env: DJANGO="Django>=1.5,<1.6"
    - python: "2.6"
      env: DJANGO="Django>=1.6,<1.7"
    - python: "3.4"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.4"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.4"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.5"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.5"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.5"
      env: DJANGO="Django>=1.11,<1.12"
    - python: "3.5"
      env: DJANGO="Django>=2.0,<2.1"
  exclude:
    - python: "2.6"
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.3"
      env: DJANGO="Django>=1.11,<1.12"
    - python: "3.3"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.4"
    - python: "3.5"
    - python: "pypy"
      env: DJANGO="Django>=2.0,<2.1"
env:
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.0,<2.1"
install:
  - pip install $DJANGO
  - pip install -e .[test]
script:
  - coverage run -m py.test advanced_filters
  - pep8 --exclude=*urls.py --exclude=*migrations advanced_filters -v
after_success:
  coveralls
